server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  http2:
    enabled: true
  port: 8901
  servlet:
    context-path: /kappa-talk
  ssl:
    enabled: true
    enabled-protocols: TLSv1.2
    key-alias: ${SSL_KEY_ALIAS:}
    key-password: ${SSL_KEY_PASSWORD:}
    key-store: classpath:vengeance.jks
    key-store-password: ${SSL_KEYSTORE_PASSWORD:}
    key-store-type: JKS
    protocol: TLS
spring:
  data:
    mongodb:
      authentication-database: ${MONGO_AUTH_DB:}
      database: ${MONGO_DB:}
      uri: ${MONGO_CONNECTION_URL:}
  banner:
    location: banner.txt
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: ${AUTH_SERVICE:}
          client-id: ${CLIENT_ID:}
          client-secret: ${CLIENT_SECRET:}
        jwt:
          jwk-set-uri: ${JWKS_ENDPOINT:}
  rabbitmq:
    host: ${RABBITMQ_HOST:}
    port: ${RABBITMQ_PORT:}
    username: ${RABBITMQ_USERNAME:}
    password: ${RABBITMQ_PASSWORD:}
    template:
      exchange: ${RABBITMQ_EXCHANGE:}
storage:
  storage-type: firebase
  temp: ${TEMP_DIR:}
  cloudinary:
    url: ${CLOUDINARY_URL:}
  firebase:
    database-url: ${FIREBASE_DATABASE_URL:}
    storage-bucket: ${FIREBASE_STORAGE_BUCKET:}
    credentials: ${FIREBASE_CREDENTIALS:}
  local:
    upload-dir: ${UPLOAD_DIR:}
custom:
  hazelcast-hosts: localhost
  http-port: 8900
  https-port: 8901
  security-policy: NONE
  connector-scheme: http
  trust-store-password: ${SSL_TRUSTSTORE_PASSWORD:}
  trust-store-type: JKS
  enable-external-broker: false
logging:
  config: classpath:log4j-spring.xml
  level:
    root: INFO

